/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import BLL.Especie;
import BLL.Raza;
import BLL.TipoMantenimiento;
import DAO.RazasDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class JDialogMantenimientoEspecieRazas extends javax.swing.JDialog {

    private TipoMantenimiento tipoMantenimiento;
    private Especie especie;
    String nombreEspecie;
    private String nombreRaza;
    private Raza raza;

    /**
     * Creates new form JDialogMantenimientoEspecieRazas
     */
    public JDialogMantenimientoEspecieRazas(java.awt.Frame parent, boolean modal) {

        initComponents();
    }

    public JDialogMantenimientoEspecieRazas(TipoMantenimiento tipoMantenimiento, Especie especie, Raza raza) {
        initComponents();
        this.setModal(true);
        this.setLocationRelativeTo(null);
        nombreEspecie = especie.getNombreEspecie();
        this.especie = especie;
        this.raza = raza;
        this.tipoMantenimiento = tipoMantenimiento;
        
        if (raza != null) {
            this.nombreRaza = raza.getNombreRaza().trim();
        }
        
        switch (tipoMantenimiento) {
            case AGREGAR -> {
                this.setTitle("Agregar raza");
                jLblNombreRaza.setText("Agregar Raza de " + nombreEspecie);
            }

            case MODIFICAR -> {
                this.setTitle("Modificar raza");
                jLblNombreRaza.setText("Nuevo nombre de la raza de " + nombreEspecie);
                jTxtNombreRaza.setText(nombreRaza.trim()
                );
            }
            case CONSULTAR -> {
                this.setTitle("Consulta de raza");
                jLblNombreRaza.setText("Raza de " + nombreEspecie);
                jTxtNombreRaza.setText(nombreRaza.trim());
                jTxtNombreRaza.setEnabled(false);
                jBtnCancelar.setEnabled(false);
                jBtnCancelar.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNombreRaza = new javax.swing.JLabel();
        jTxtNombreRaza = new javax.swing.JTextField();
        jBtnAceptar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblNombreRaza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTxtNombreRaza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNombreRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombreRazaActionPerformed(evt);
            }
        });

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblNombreRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtNombreRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLblNombreRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTxtNombreRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        // TODO add your handling code here:

        switch (this.tipoMantenimiento) {
            case AGREGAR -> {
                Raza raza = null;
                nombreRaza = jTxtNombreRaza.getText();

                if (!nombreRaza.isBlank()) {
                    raza = new Raza(nombreRaza, especie.getCodigoEspecie());

                    if (raza != null) {
                        Raza.agregarRaza(raza);
                        JOptionPane.showMessageDialog(null, "Raza agregada correctamente", "¡Raza agregada!", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al agregar la raza");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes escribir en el espacio del nombre de la raza", "Nombre de raza vacío", JOptionPane.ERROR_MESSAGE);
                }
            }

            case MODIFICAR -> {
                if (!jTxtNombreRaza.getText().isBlank()) {
                    String nuevoNombre = jTxtNombreRaza.getText().trim();
                    Raza.modificarRaza(nuevoNombre,raza.getId_raza());
                    
                    JOptionPane.showMessageDialog(null, "La raza de " + this.nombreEspecie + " '" + nombreRaza + "' ahora se llama '" + nuevoNombre + "'",
                            "Raza modificada", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
            case CONSULTAR ->
                this.dispose();
        }
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtNombreRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreRazaActionPerformed
        // TODO add your handling code here:
        jBtnAceptar.doClick();
    }//GEN-LAST:event_jTxtNombreRazaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JLabel jLblNombreRaza;
    private javax.swing.JTextField jTxtNombreRaza;
    // End of variables declaration//GEN-END:variables
}
