/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import BLL.Especie;
import BLL.Gato;
import BLL.Perro;
import BLL.TipoMantenimiento;
import BLL_Motivos.Vacuna;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class JDialogMantenimientoVacunas extends javax.swing.JDialog {

    TipoMantenimiento tipoMantenimiento;
    Vacuna vacunaEntrada;

    /**
     * Creates new form JDialogMantenimientoVacunas
     */
    public JDialogMantenimientoVacunas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDialogMantenimientoVacunas(TipoMantenimiento tipoMantenimiento, Vacuna vacuna) {
        initComponents();
        this.setModal(true);
        this.tipoMantenimiento = tipoMantenimiento;

        switch (tipoMantenimiento) {
            case AGREGAR -> {
                this.setTitle("Agregar Vacuna");
            }
            case MODIFICAR -> {
                this.setTitle("Modificar Vacuna " + vacuna.getNombre().trim());
                vacunaEntrada = vacuna;
                jTxtNombreVacuna.setText(vacuna.getNombre().trim());
                jTxtPrecio.setText(String.valueOf(vacuna.getPrecio()));

                if (vacuna.getEspecieVacuna().getId_especie() == 1) {
                    jRbdPerro.setSelected(true);
                } else if (vacuna.getEspecieVacuna().getId_especie() == 2) {
                    jRbdGato.setSelected(true);
                }
            }
            case CONSULTAR -> {
                this.setTitle("Consultar sobre: " + vacuna.getNombre().trim());
                vacunaEntrada = vacuna;
                jTxtNombreVacuna.setText(vacuna.getNombre().trim());
                jTxtNombreVacuna.setEditable(false);
                
                jTxtPrecio.setText(String.valueOf(vacuna.getPrecio()));
                jTxtPrecio.setEditable(false);

                if (vacuna.getEspecieVacuna().getId_especie() == 1) {
                    jRbdPerro.setSelected(true);
                } else if (vacuna.getEspecieVacuna().getId_especie() == 2) {
                    jRbdGato.setSelected(true);
                }
                
                jRbdPerro.setEnabled(false);
                jRbdGato.setEnabled(false);
                jBtnAceptar.setText("Salir");
                jBtnCancelar.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEspecies = new javax.swing.ButtonGroup();
        jLblNombreVacuna = new javax.swing.JLabel();
        jTxtNombreVacuna = new javax.swing.JTextField();
        jLblPrecio = new javax.swing.JLabel();
        jTxtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRbdPerro = new javax.swing.JRadioButton();
        jRbdGato = new javax.swing.JRadioButton();
        jBtnAceptar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblNombreVacuna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNombreVacuna.setText("Nombre de la vacuna");

        jTxtNombreVacuna.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNombreVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombreVacunaActionPerformed(evt);
            }
        });

        jLblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPrecio.setText("Precio de la vacuna");

        jTxtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPrecioActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vacuna para:");

        buttonGroupEspecies.add(jRbdPerro);
        jRbdPerro.setText("Perro");
        jRbdPerro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRbdPerro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        buttonGroupEspecies.add(jRbdGato);
        jRbdGato.setText("Gato");
        jRbdGato.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.setPreferredSize(new java.awt.Dimension(80, 27));
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRbdPerro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRbdGato))
                    .addComponent(jLblNombreVacuna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTxtPrecio)
                    .addComponent(jTxtNombreVacuna, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLblNombreVacuna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNombreVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLblPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbdPerro)
                    .addComponent(jRbdGato))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        // TODO add your handling code here:
        switch (tipoMantenimiento) {
            case AGREGAR -> {
                if (verificarCampos()) {
                    try {
                        Vacuna vacuna = crearVacuna();
                        Vacuna.agregarVacuna(vacuna);
                        JOptionPane.showMessageDialog(null, "La vacuna " + vacuna.getNombre() + " a sido agregada", "¡Vacuna agregada!", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Debes ingresar un numero en el precio", "Campo no válido", JOptionPane.ERROR_MESSAGE);
                    } catch (Exception e) {
                        Logger.getLogger(JDialogMantenimientoVacunas.class.getName()).log(Level.SEVERE, null, e);
                    }
                }
            }
            case MODIFICAR -> {
                if (verificarCampos()) {
                    try {
                        Vacuna vacuna = crearVacuna();

                        Vacuna.modificarVacuna(vacuna, vacunaEntrada.getId_vacuna());
                        JOptionPane.showMessageDialog(null, "La vacuna se modifico correctamente", "¡Vacuna modificada!", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Debes ingresar un numero en el precio", "Campo no válido", JOptionPane.ERROR_MESSAGE);
                    } catch (Exception e) {
                        Logger.getLogger(JDialogMantenimientoVacunas.class.getName()).log(Level.SEVERE, null, e);
                    }
                }
            }
            case CONSULTAR -> {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtNombreVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreVacunaActionPerformed
        // TODO add your handling code here:
        jTxtPrecio.requestFocus();
    }//GEN-LAST:event_jTxtNombreVacunaActionPerformed

    private void jTxtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPrecioActionPerformed
        // TODO add your handling code here:
        jBtnAceptar.doClick();
    }//GEN-LAST:event_jTxtPrecioActionPerformed

    private Especie crearEspecie() {
        return (jRbdPerro.isSelected()) ? new Perro()
                : (jRbdGato.isSelected()) ? new Gato()
                : null;
    }

    private Vacuna crearVacuna() throws Exception {
        try {
            String nombreVacuna = jTxtNombreVacuna.getText().trim();

            double precio = Double.parseDouble(jTxtPrecio.getText().trim());

            Especie especie = crearEspecie();

            Vacuna vacuna = new Vacuna(nombreVacuna, precio, especie);

            return vacuna;

        } catch (NumberFormatException e) {
            throw e;
        }
    }

    private boolean verificarCampos() {
        if (jTxtNombreVacuna.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar el nombre de la vacuna", "Campo vacíos", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (jTxtPrecio.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar el precio de la vacuna", "Campo vacíos", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!jRbdPerro.isSelected() && !jRbdGato.isSelected()) {
            JOptionPane.showMessageDialog(null, "Debes elegir la especie para la vacuna", "Campo vacíos", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupEspecies;
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblNombreVacuna;
    private javax.swing.JLabel jLblPrecio;
    private javax.swing.JRadioButton jRbdGato;
    private javax.swing.JRadioButton jRbdPerro;
    private javax.swing.JTextField jTxtNombreVacuna;
    private javax.swing.JTextField jTxtPrecio;
    // End of variables declaration//GEN-END:variables
}
