/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BLL.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class jFrameInicioSesion extends javax.swing.JFrame {

    private List<Usuario> arrayUsuarios = new ArrayList<>(); 
    private int numeroIntentos = 0;
    /**
     * Creates new form jFrameInicioSesion
     */
    public jFrameInicioSesion() {
        initComponents();
        crearUsuarios();
        jTxtUsuario.setText("admin");
        jPwdContraseña.setText("123456");
    }
    
    public void crearUsuarios(){
        arrayUsuarios.add(new Usuario("admin", "123456"));
        arrayUsuarios.add(new Usuario("Andrey", "123321"));
        arrayUsuarios.add(new Usuario("Ivannia", "221133"));
        arrayUsuarios.add(new Usuario("Alexis", "112233"));
        arrayUsuarios.add(new Usuario("Laura", "123456"));
        arrayUsuarios.add(new Usuario("Alejandro", "111111"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPwdContraseña = new javax.swing.JPasswordField();
        jLblContraseña = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jLblUsuario = new javax.swing.JLabel();
        jBtnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPwdContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPwdContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwdContraseñaActionPerformed(evt);
            }
        });

        jLblContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblContraseña.setText("Contraseña");

        jTxtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUsuarioActionPerformed(evt);
            }
        });

        jLblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblUsuario.setText("Usuario");

        jBtnIngresar.setText("Ingresar");
        jBtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jPwdContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblContraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jBtnIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPwdContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnIngresar)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPwdContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwdContraseñaActionPerformed
        // TODO add your handling code here:
        jBtnIngresar.doClick();
    }//GEN-LAST:event_jPwdContraseñaActionPerformed

    private void jTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUsuarioActionPerformed
        // TODO add your handling code here:
        jPwdContraseña.requestFocus();
    }//GEN-LAST:event_jTxtUsuarioActionPerformed

    private void jBtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresarActionPerformed
        // TODO add your handling code here:
        String nombreUsuario = jTxtUsuario.getText();
        String contrasenia = "";
        for (char letra : jPwdContraseña.getPassword()) {
            contrasenia += letra;
        }
        
        boolean existeNombre = false;
        boolean existeContrasenia = false;

        for (Usuario usuario : arrayUsuarios) {
            if (usuario.getNombreUsuario().equals(nombreUsuario)) {
                existeNombre = true;
                if (usuario.getContrasenia().equals(contrasenia)) {
                    existeContrasenia = true;
                    break;
                }
            }
        }
        if (existeNombre & existeContrasenia) {
            JOptionPane.showMessageDialog(null, "Bienvenido " + nombreUsuario, "", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            MdiPrincipal ventanaPrincipal = new MdiPrincipal(nombreUsuario);
            ventanaPrincipal.setVisible(true);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "El usuario no existe", "Usuario inexistente", JOptionPane.INFORMATION_MESSAGE);
        }
        
        numeroIntentos++;
        
        if (numeroIntentos >= 3) {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado la cantidad máxima de intentos \nSe cerrará la aplicación por intentos fallidos", "Límite de intentos alcanzado", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_jBtnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIngresar;
    private javax.swing.JLabel jLblContraseña;
    private javax.swing.JLabel jLblUsuario;
    private javax.swing.JPasswordField jPwdContraseña;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
