/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BLL.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class jFrameInicioSesion extends javax.swing.JFrame {

    private List<Usuario> arrayUsuarios = new ArrayList<>(); 
    private int numeroIntentos = 0;
    /**
     * Creates new form jFrameInicioSesion
     */
    public jFrameInicioSesion() {
        initComponents();
        crearUsuarios();
        jTxtUsuario.setText("admin");
        jPwdContraseña.setText("123456");
    }
    
    public void crearUsuarios(){
        arrayUsuarios.add(new Usuario("admin", "123456"));
        arrayUsuarios.add(new Usuario("Andrey", "123321"));
        arrayUsuarios.add(new Usuario("Ivannia", "221133"));
        arrayUsuarios.add(new Usuario("Alexis", "112233"));
        arrayUsuarios.add(new Usuario("Laura", "123456"));
        arrayUsuarios.add(new Usuario("Alejandro", "111111"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new PonerImagenPanel("/Imagenes/FondoInicioSesion2.jpg");
        jPwdContraseña = new javax.swing.JPasswordField();
        jLblContraseña = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jLblUsuario = new javax.swing.JLabel();
        jBtnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPwdContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPwdContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwdContraseñaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 213;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 48, 0, 49);
        jPanel1.add(jPwdContraseña, gridBagConstraints);

        jLblContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblContraseña.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 221;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 48, 0, 49);
        jPanel1.add(jLblContraseña, gridBagConstraints);

        jTxtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 214;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 47, 0, 49);
        jPanel1.add(jTxtUsuario, gridBagConstraints);

        jLblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblUsuario.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 242;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 47, 0, 49);
        jPanel1.add(jLblUsuario, gridBagConstraints);

        jBtnIngresar.setText("Ingresar");
        jBtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 59, 0);
        jPanel1.add(jBtnIngresar, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPwdContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwdContraseñaActionPerformed
        // TODO add your handling code here:
        jBtnIngresar.doClick();
    }//GEN-LAST:event_jPwdContraseñaActionPerformed

    private void jTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUsuarioActionPerformed
        // TODO add your handling code here:
        jPwdContraseña.requestFocus();
    }//GEN-LAST:event_jTxtUsuarioActionPerformed

    private void jBtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresarActionPerformed
        // TODO add your handling code here:
        String nombreUsuario = jTxtUsuario.getText();
        String contrasenia = "";
        for (char letra : jPwdContraseña.getPassword()) {
            contrasenia += letra;
        }
        
        boolean existeNombre = false;
        boolean existeContrasenia = false;

        for (Usuario usuario : arrayUsuarios) {
            if (usuario.getNombreUsuario().equals(nombreUsuario)) {
                existeNombre = true;
                if (usuario.getContrasenia().equals(contrasenia)) {
                    existeContrasenia = true;
                    break;
                }
            }
        }
        if (existeNombre & existeContrasenia) {
            JOptionPane.showMessageDialog(null, "Bienvenido " + nombreUsuario, "", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            MdiPrincipal ventanaPrincipal = new MdiPrincipal(nombreUsuario);
            ventanaPrincipal.setVisible(true);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "El usuario no existe", "Usuario inexistente", JOptionPane.INFORMATION_MESSAGE);
        }
        
        numeroIntentos++;
        
        if (numeroIntentos >= 3) {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado la cantidad máxima de intentos \nSe cerrará la aplicación por intentos fallidos", "Límite de intentos alcanzado", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_jBtnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIngresar;
    private javax.swing.JLabel jLblContraseña;
    private javax.swing.JLabel jLblUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPwdContraseña;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
