/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;

import BLL.*;
import BLL_Motivos.Vacuna;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
/**
 *
 * @author andre
 */
public class JInternalMantenimientoVacunas extends javax.swing.JInternalFrame {

    List<Vacuna> arrayVacunasPerros = new ArrayList<>();
    List<Vacuna> arrayVacunasGatos = new ArrayList<>();
    DefaultListModel modeloLista = new DefaultListModel();
    
    public JInternalMantenimientoVacunas() {
        initComponents();
        jListVacunas.setModel(modeloLista);
        llenarComboBox();
        actualizarLista();
        llenarLista();
    }
    
    private void llenarComboBox(){
        try {
            jCmbEspecies.setModel(new DefaultComboBoxModel(Especie.ConsultarEspecies().toArray()));
        } catch (Exception ex) {
            Logger.getLogger(JInternalMantenimientoVacunas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void llenarLista(){
        modeloLista.clear();
        if (((Especie)jCmbEspecies.getSelectedItem()).getCodigoEspecie() == 1) {
            modeloLista.addAll(arrayVacunasPerros);
        }
        else{
            modeloLista.addAll(arrayVacunasGatos);
        }
    }
    
    private void actualizarLista(){
        try {
            for (Vacuna vacuna : Vacuna.consultarVacunas()) {
                if (vacuna.getEspecieVacuna().getCodigoEspecie() == 1) {
                    arrayVacunasPerros.add(vacuna);
                }
                else{
                    arrayVacunasGatos.add(vacuna);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(JInternalMantenimientoVacunas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCmbEspecies = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnAgregar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnConsultar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListVacunas = new javax.swing.JList<>();

        setTitle("Mantenimiento de vacunas");

        jCmbEspecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbEspeciesActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Especie de la vacuna");

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.setPreferredSize(new java.awt.Dimension(110, 30));
        jPanel1.add(jBtnAgregar);

        jBtnModificar.setText("Modificar");
        jBtnModificar.setPreferredSize(new java.awt.Dimension(110, 30));
        jPanel1.add(jBtnModificar);

        jBtnConsultar.setText("Consultar");
        jBtnConsultar.setPreferredSize(new java.awt.Dimension(110, 30));
        jPanel1.add(jBtnConsultar);

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.setPreferredSize(new java.awt.Dimension(110, 30));
        jPanel1.add(jBtnEliminar);

        jListVacunas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListVacunas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jCmbEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCmbEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbEspeciesActionPerformed
        // TODO add your handling code here:
        llenarLista();
    }//GEN-LAST:event_jCmbEspeciesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JComboBox<Especie> jCmbEspecies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Vacuna> jListVacunas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
