/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;

import BLL.*;
import BLL_Motivos.Motivo;
import BLL_Motivos.Vacuna;
import BLL_Motivos.Vacunacion;
import BLL_PruebaLaboratorio.SubCategoriaPrueba;
import BLL_PruebaLaboratorio.PruebaLaboratorio;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author andre
 */
public class JInternalProcesoCita extends javax.swing.JInternalFrame {

    DefaultListModel<Dueño> modeloListaDuenos = new DefaultListModel<>();
    DefaultListModel<Paciente> modeloListaPacientes = new DefaultListModel<>();
    DefaultListModel<Motivo> modeloListaMotivos = new DefaultListModel<>();
    DefaultListModel<SubCategoriaPrueba> modeloListaSubCategoriasPruebaLaboratorio = new DefaultListModel<>();
    
    DefaultTableModel modeloTablaMotivos;
    List<Raza> arrayRazasPerros;
    List<Raza> arrayRazasGatos;
    List<Dueño> arrayDueños;
    List<Motivo> arrayMotivos;
    List<SubCategoriaPrueba> arrayTodasLasSubCategorias;
    List<SubCategoriaPrueba> arraySubCategorias;
    Dueño dueno;
    Paciente paciente;
    
    /**
     * 
     * Creates new form JInternalProcesoCIta
     */
    public JInternalProcesoCita() {
        initComponents();
        jListDueno.setModel(modeloListaDuenos);
        jListPaciente.setModel(modeloListaPacientes);
        actualizararrayDuenos();
        modeloListaDuenos.addAll(arrayDueños);
        jCmbSexo.setModel(new DefaultComboBoxModel<>(Sexo.values()));
        try {
            jCmbEspecie.setModel(new DefaultComboBoxModel(Especie.consultarEspecies().toArray()));
            
            jCmbVacunas.setModel(new DefaultComboBoxModel(Vacuna.consultarVacunas().toArray()));
            
            arrayTodasLasSubCategorias = SubCategoriaPrueba.consultarSubCategorias();
            
        } catch (Exception ex) {
            Logger.getLogger(JInternalProcesoCita.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        CrearListaRazas();
        jCmbRaza.setModel(new DefaultComboBoxModel(arrayRazasPerros.toArray()));
        
        jListMotivos.setModel(modeloListaMotivos);
        jListSubCategorias.setModel(modeloListaSubCategoriasPruebaLaboratorio);
        llenarListaMotivos();
        llenarComboBoxPruebasLaboratorio();
        llenarListaSubCategorias();
        arrayMotivos = new ArrayList<>();
        arraySubCategorias = new ArrayList<>();
        modeloTablaMotivos = (DefaultTableModel)jTableMotivosElegidos.getModel();
        
        jCmbVacunas.setVisible(false);
        jLblVacunas.setVisible(false);
        jTxtPrecioMotivo.setEditable(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPlProcesoCita = new javax.swing.JTabbedPane();
        jPanelPaciente = new PanelConFondo("/Imagenes/FondoCitas.png");
        jPanelDueno = new javax.swing.JPanel();
        jLblNombreDueno = new javax.swing.JLabel();
        jTxtNombreDueno = new javax.swing.JTextField();
        jLblDireccion = new javax.swing.JLabel();
        jTxtDireccionDueno = new javax.swing.JTextField();
        jLblNumeroTelefono = new javax.swing.JLabel();
        jFTxtNumeroTelefono = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDueno = new javax.swing.JList<>();
        jLblDuenos = new javax.swing.JLabel();
        jBtnElegirDueno = new javax.swing.JButton();
        jBtnAnadirNuevoDueno = new javax.swing.JButton();
        jFTxtNumeroCedula = new javax.swing.JFormattedTextField();
        jLblCedula = new javax.swing.JLabel();
        jBtnLimpiarDueno = new javax.swing.JButton();
        jPanelDatosPaciente = new javax.swing.JPanel();
        jLblNombrePaciente = new javax.swing.JLabel();
        jTxtNombrePaciente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPaciente = new javax.swing.JList<>();
        jLblPacientes = new javax.swing.JLabel();
        jBtnElegirPaciente = new javax.swing.JButton();
        jBtnAnadirNuevoPaciente = new javax.swing.JButton();
        jLblSexoPaciente = new javax.swing.JLabel();
        jLblEdad = new javax.swing.JLabel();
        jLblEspecie = new javax.swing.JLabel();
        jCmbEspecie = new javax.swing.JComboBox<>();
        jCmbSexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSprEdad = new javax.swing.JSpinner();
        jLblEdad1 = new javax.swing.JLabel();
        jLblEspecie1 = new javax.swing.JLabel();
        jCmbRaza = new javax.swing.JComboBox<>();
        jBtnLimpiarPaciente = new javax.swing.JButton();
        jLblDuenoElegido = new javax.swing.JLabel();
        jPanelCita = new PanelConFondo("/Imagenes/FondoCitas.png");
        jPanel3 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jPanelMotivo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListMotivos = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jTxtPrecioMotivo = new javax.swing.JTextField();
        jCmbVacunas = new javax.swing.JComboBox<>();
        jLblVacunas = new javax.swing.JLabel();
        jBtnAgregarMotivo = new javax.swing.JButton();
        jPanelPrueba = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListSubCategorias = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jCmbPruebasLaboratorio = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanelMotivosElegidos = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMotivosElegidos = new javax.swing.JTable();
        jBtnEliminarMotivo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablePruebasElegidas = new javax.swing.JTable();
        jBtnEliminarPrueba = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Proceso de citas");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanelDueno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del dueño"));
        jPanelDueno.setOpaque(false);

        jLblNombreDueno.setText("Nombre");

        jTxtNombreDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombreDuenoActionPerformed(evt);
            }
        });

        jLblDireccion.setText("Dirección");

        jTxtDireccionDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDireccionDuenoActionPerformed(evt);
            }
        });

        jLblNumeroTelefono.setText("Numero de teléfono");

        try {
            jFTxtNumeroTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTxtNumeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTxtNumeroTelefonoActionPerformed(evt);
            }
        });

        jListDueno.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListDueno);

        jLblDuenos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblDuenos.setText("Lista de dueños");

        jBtnElegirDueno.setText("Elegir dueño seleccionado");
        jBtnElegirDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElegirDuenoActionPerformed(evt);
            }
        });

        jBtnAnadirNuevoDueno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarDueño.png"))); // NOI18N
        jBtnAnadirNuevoDueno.setText("Añadir nuevo dueño");
        jBtnAnadirNuevoDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnadirNuevoDuenoActionPerformed(evt);
            }
        });

        try {
            jFTxtNumeroCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTxtNumeroCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTxtNumeroCedulaActionPerformed(evt);
            }
        });
        jFTxtNumeroCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFTxtNumeroCedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTxtNumeroCedulaKeyTyped(evt);
            }
        });

        jLblCedula.setText("Cédula");

        jBtnLimpiarDueno.setText("Limpiar");
        jBtnLimpiarDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarDuenoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDuenoLayout = new javax.swing.GroupLayout(jPanelDueno);
        jPanelDueno.setLayout(jPanelDuenoLayout);
        jPanelDuenoLayout.setHorizontalGroup(
            jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDuenoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDuenoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnAnadirNuevoDueno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDuenoLayout.createSequentialGroup()
                                .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblNumeroTelefono)
                                    .addComponent(jLblCedula)
                                    .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLblDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblNombreDueno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtDireccionDueno)
                                    .addComponent(jTxtNombreDueno)
                                    .addComponent(jFTxtNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTxtNumeroCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLblDuenos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDuenoLayout.createSequentialGroup()
                        .addComponent(jBtnLimpiarDueno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnElegirDueno)))
                .addContainerGap())
        );
        jPanelDuenoLayout.setVerticalGroup(
            jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDuenoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTxtNumeroCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtNombreDueno)
                    .addComponent(jLblNombreDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDireccionDueno))
                .addGap(18, 18, 18)
                .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTxtNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnAnadirNuevoDueno)
                .addGap(18, 18, 18)
                .addComponent(jLblDuenos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDuenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnElegirDueno)
                    .addComponent(jBtnLimpiarDueno))
                .addContainerGap())
        );

        jPanelDatosPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del paciente"));
        jPanelDatosPaciente.setOpaque(false);

        jLblNombrePaciente.setText("Nombre");

        jTxtNombrePaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombrePacienteKeyTyped(evt);
            }
        });

        jListPaciente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListPaciente);

        jLblPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPacientes.setText("Lista de pacientes por dueño");

        jBtnElegirPaciente.setText("Elegir paciente seleccionado");
        jBtnElegirPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElegirPacienteActionPerformed(evt);
            }
        });

        jBtnAnadirNuevoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarPaciente.png"))); // NOI18N
        jBtnAnadirNuevoPaciente.setText("Añadir nuevo paciente");
        jBtnAnadirNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnadirNuevoPacienteActionPerformed(evt);
            }
        });

        jLblSexoPaciente.setText("Sexo");

        jLblEdad.setText("Edad");

        jLblEspecie.setText("Especie");

        jCmbEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbEspecieActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perro.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gato.png"))); // NOI18N

        jSprEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 300, 1));

        jLblEdad1.setText("Meses");

        jLblEspecie1.setText("Raza");

        jBtnLimpiarPaciente.setText("Limpiar");
        jBtnLimpiarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosPacienteLayout = new javax.swing.GroupLayout(jPanelDatosPaciente);
        jPanelDatosPaciente.setLayout(jPanelDatosPacienteLayout);
        jPanelDatosPacienteLayout.setHorizontalGroup(
            jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addGroup(jPanelDatosPacienteLayout.createSequentialGroup()
                        .addComponent(jLblPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblEspecie)
                            .addComponent(jLblSexoPaciente)
                            .addComponent(jLblEdad)
                            .addComponent(jLblEspecie1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosPacienteLayout.createSequentialGroup()
                                .addComponent(jSprEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblEdad1))
                            .addComponent(jCmbRaza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPacienteLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbEspecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jCmbSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtNombrePaciente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPacienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnAnadirNuevoPaciente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPacienteLayout.createSequentialGroup()
                        .addComponent(jBtnLimpiarPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnElegirPaciente)))
                .addContainerGap())
        );
        jPanelDatosPacienteLayout.setVerticalGroup(
            jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPacienteLayout.createSequentialGroup()
                        .addComponent(jLblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblSexoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLblEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblEspecie1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPacienteLayout.createSequentialGroup()
                        .addComponent(jTxtNombrePaciente)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSprEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jCmbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jCmbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAnadirNuevoPaciente)
                .addGap(12, 12, 12)
                .addComponent(jLblPacientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnElegirPaciente)
                    .addComponent(jBtnLimpiarPaciente))
                .addContainerGap())
        );

        jLblDuenoElegido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblDuenoElegido.setText("Dueño no elegido");

        javax.swing.GroupLayout jPanelPacienteLayout = new javax.swing.GroupLayout(jPanelPaciente);
        jPanelPaciente.setLayout(jPanelPacienteLayout);
        jPanelPacienteLayout.setHorizontalGroup(
            jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPacienteLayout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(jPanelDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLblDuenoElegido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatosPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(218, 218, 218))
        );
        jPanelPacienteLayout.setVerticalGroup(
            jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacienteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLblDuenoElegido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDueno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatosPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTPlProcesoCita.addTab("Paciente", jPanelPaciente);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de la cita"));
        jPanel3.setOpaque(false);

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fecha");

        jPanelMotivo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Motivo de la cita"));
        jPanelMotivo.setOpaque(false);

        jListMotivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListMotivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListMotivosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListMotivos);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Precio");

        jTxtPrecioMotivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jCmbVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbVacunasActionPerformed(evt);
            }
        });

        jLblVacunas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVacunas.setText("Vacunas");

        jBtnAgregarMotivo.setText("Agregar motivo");
        jBtnAgregarMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarMotivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMotivoLayout = new javax.swing.GroupLayout(jPanelMotivo);
        jPanelMotivo.setLayout(jPanelMotivoLayout);
        jPanelMotivoLayout.setHorizontalGroup(
            jPanelMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanelMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmbVacunas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblVacunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtPrecioMotivo)
                    .addComponent(jBtnAgregarMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMotivoLayout.setVerticalGroup(
            jPanelMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMotivoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtPrecioMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblVacunas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmbVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAgregarMotivo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPrueba.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pruebas de laboratorio"));
        jPanelPrueba.setOpaque(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pruebas de laboratorio");

        jListSubCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jListSubCategorias);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tipo de prueba");

        jCmbPruebasLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbPruebasLaboratorioActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar prueba");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPruebaLayout = new javax.swing.GroupLayout(jPanelPrueba);
        jPanelPrueba.setLayout(jPanelPruebaLayout);
        jPanelPruebaLayout.setHorizontalGroup(
            jPanelPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPruebaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPruebaLayout.createSequentialGroup()
                        .addGroup(jPanelPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPruebaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPruebaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCmbPruebasLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanelPruebaLayout.setVerticalGroup(
            jPanelPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPruebaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCmbPruebasLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(106, 106, 106))
        );

        jPanelMotivosElegidos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Motivos elegidos"));
        jPanelMotivosElegidos.setOpaque(false);

        jTableMotivosElegidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Motivo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMotivosElegidos.setOpaque(false);
        jScrollPane5.setViewportView(jTableMotivosElegidos);

        jBtnEliminarMotivo.setText("Eliminar");
        jBtnEliminarMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarMotivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMotivosElegidosLayout = new javax.swing.GroupLayout(jPanelMotivosElegidos);
        jPanelMotivosElegidos.setLayout(jPanelMotivosElegidosLayout);
        jPanelMotivosElegidosLayout.setHorizontalGroup(
            jPanelMotivosElegidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotivosElegidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMotivosElegidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMotivosElegidosLayout.createSequentialGroup()
                        .addGap(0, 217, Short.MAX_VALUE)
                        .addComponent(jBtnEliminarMotivo)))
                .addContainerGap())
        );
        jPanelMotivosElegidosLayout.setVerticalGroup(
            jPanelMotivosElegidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotivosElegidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEliminarMotivo)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pruebas elegidas"));
        jPanel1.setOpaque(false);

        jTablePruebasElegidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo prueba", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePruebasElegidas.setOpaque(false);
        jScrollPane6.setViewportView(jTablePruebasElegidas);

        jBtnEliminarPrueba.setText("Eliminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnEliminarPrueba)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEliminarPrueba)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelPrueba, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMotivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMotivosElegidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMotivosElegidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton1.setText("Probar motivos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Probar pruebas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCitaLayout = new javax.swing.GroupLayout(jPanelCita);
        jPanelCita.setLayout(jPanelCitaLayout);
        jPanelCitaLayout.setHorizontalGroup(
            jPanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addGroup(jPanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelCitaLayout.setVerticalGroup(
            jPanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCitaLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTPlProcesoCita.addTab("Cita", jPanelCita);

        getContentPane().add(jTPlProcesoCita);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     // <editor-fold defaultstate="collapsed" desc="Codigo de Dueño y paciente">
    private void jFTxtNumeroCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTxtNumeroCedulaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFTxtNumeroCedulaKeyTyped

    private void actualizararrayDuenos(){
        try {
            arrayDueños = Dueño.cosultarDueños();
        } catch (Exception ex) {
            Logger.getLogger(JInternalProcesoCita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void CrearListaRazas(){
        try {
            arrayRazasPerros = new ArrayList<>();
            arrayRazasGatos = new ArrayList<>();
            for (Raza raza : Raza.consultarRazas()) {
                if (raza.getEspecieAQuePertenece().getId_especie() == 1) {
                    arrayRazasPerros.add(raza);
                }
                else if (raza.getEspecieAQuePertenece().getId_especie() == 2) {
                    arrayRazasGatos.add(raza);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(JInternalMantenimientoEspeciesRazas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jBtnAnadirNuevoDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnadirNuevoDuenoActionPerformed
        // TODO add your handling code here:
        String cedula = jFTxtNumeroCedula.getText().replace("-", "").trim();
        String nombre = jTxtNombreDueno.getText().trim();
        String direccion = jTxtDireccionDueno.getText().trim();
        String numero_telefono = jFTxtNumeroTelefono.getText().replace("-", "").trim();

        try {
            if (modeloListaDuenos.get(0).getCedula().equals(cedula)) {
                JOptionPane.showMessageDialog(null, "El Dueño solo fue elegido porque ya existe", "Dueño ya existente", JOptionPane.ERROR_MESSAGE);
                dueno = modeloListaDuenos.get(0);
                jTxtNombreDueno.setText(dueno.getNombre());
                jTxtDireccionDueno.setText(dueno.getDireccion());
                jFTxtNumeroTelefono.setText(dueno.getTelefono());
                accionesDefinirDueño();
                return;
            }
        } catch (Exception e) {
        }

        if (cedula.isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar la cédula del dueño", "Espacio en blanco", JOptionPane.ERROR_MESSAGE);
        } else if (nombre.isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar el nombre del dueño", "Espacio en blanco", JOptionPane.ERROR_MESSAGE);
        } else if (direccion.isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar la direccion del dueño", "Espacio en blanco", JOptionPane.ERROR_MESSAGE);
        } else if (numero_telefono.isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar el número de teléfono del dueño", "Espacio en blanco", JOptionPane.ERROR_MESSAGE);
        } else {

            try {
                dueno = new Dueño(cedula, nombre, direccion, numero_telefono);
                Dueño.agregar(dueno);
                actualizararrayDuenos();
                modeloListaDuenos.addAll(arrayDueños);
                accionesDefinirDueño();
                JOptionPane.showMessageDialog(null, "El dueño fue creado correctamete", "!Dueño creado¡", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(JInternalProcesoCita.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBtnAnadirNuevoDuenoActionPerformed

    private void cambiarEstadoEspaciosDueno(boolean estado){
        jTxtNombreDueno.setEditable(estado);
        jFTxtNumeroCedula.setEditable(estado);
        jTxtDireccionDueno.setEditable(estado);
        jFTxtNumeroTelefono.setEditable(estado);
        jBtnAnadirNuevoDueno.setEnabled(estado);
        jBtnElegirDueno.setEnabled(estado);
    }

    private void jFTxtNumeroCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTxtNumeroCedulaKeyPressed

        modeloListaDuenos.clear();
        for (Dueño dueno : arrayDueños) {
            if (dueno.getCedula().contains(jFTxtNumeroCedula.getText().replace("-", "").trim())) {
                modeloListaDuenos.addElement(dueno);

            }
        }
    }//GEN-LAST:event_jFTxtNumeroCedulaKeyPressed

    private void jFTxtNumeroCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTxtNumeroCedulaActionPerformed
        // TODO add your handling code here:
        jTxtNombreDueno.requestFocus();
    }//GEN-LAST:event_jFTxtNumeroCedulaActionPerformed

    private void jTxtNombreDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreDuenoActionPerformed
        // TODO add your handling code here:
        jTxtDireccionDueno.requestFocus();
    }//GEN-LAST:event_jTxtNombreDuenoActionPerformed

    private void jTxtDireccionDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDireccionDuenoActionPerformed
        // TODO add your handling code here:
        jFTxtNumeroTelefono.requestFocus();
    }//GEN-LAST:event_jTxtDireccionDuenoActionPerformed

    private void jFTxtNumeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTxtNumeroTelefonoActionPerformed
        // TODO add your handling code here:
        jBtnAnadirNuevoDueno.doClick();
    }//GEN-LAST:event_jFTxtNumeroTelefonoActionPerformed

    private void jBtnElegirDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElegirDuenoActionPerformed
        // TODO add your handling code here:
        if (jListDueno.getSelectedIndex() != -1) {
            dueno = jListDueno.getSelectedValue();
            jFTxtNumeroCedula.setText(dueno.getCedula());
            jTxtNombreDueno.setText(dueno.getNombre());
            jTxtDireccionDueno.setText(dueno.getDireccion());
            jFTxtNumeroTelefono.setText(dueno.getTelefono());
            accionesDefinirDueño();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debes elegir un dueño de la lista", "Dueño no elegido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnElegirDuenoActionPerformed

    private void jBtnLimpiarDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarDuenoActionPerformed
        // TODO add your handling code here:
        jFTxtNumeroCedula.setText("");
        jTxtNombreDueno.setText("");
        jTxtDireccionDueno.setText("");
        jFTxtNumeroTelefono.setText("");
        modeloListaDuenos.clear();
        modeloListaDuenos.addAll(arrayDueños);
        jLblDuenoElegido.setText("Dueño no elegido");
        dueno = null;
        modeloListaPacientes.clear();
        if (jBtnLimpiarDueno.getText().equals("Cambiar dueño")) {
            jBtnLimpiarPaciente.doClick();
            jBtnLimpiarDueno.setText("Limpiar");
            cambiarEstadoEspaciosDueno(true);
        }
    }//GEN-LAST:event_jBtnLimpiarDuenoActionPerformed

    private void jBtnAnadirNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnadirNuevoPacienteActionPerformed
        // TODO add your handling code here:
        if (dueno != null) {

            String nombrePaciente = jTxtNombrePaciente.getText().trim();
            for (int i = 0; i < modeloListaPacientes.getSize(); i++) {
                Paciente paciente = modeloListaPacientes.getElementAt(i);
                if (paciente.getNombre().trim().equalsIgnoreCase(nombrePaciente)) {
                    int opcion = JOptionPane.showConfirmDialog(null, "Hay un paciente con el mismo nombre, ¿Seguro que quieres crear otro?", "Paciente con el mismo nombre",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (opcion == JOptionPane.YES_OPTION) {
                        break;
                    } else {
                        jListPaciente.setSelectedValue(paciente, true);
                        jBtnElegirPaciente.doClick();
                        return;
                    }
                }
            }
            if (nombrePaciente.isBlank()) {
                JOptionPane.showMessageDialog(null, "Debes ingresar el nombre del paciente", "Espacio en blanco", JOptionPane.ERROR_MESSAGE);
            } else {
                Especie especie = (Especie) jCmbEspecie.getSelectedItem();
                Raza raza = (Raza) jCmbRaza.getSelectedItem();
                raza.setEspecieAQuePertenece(especie);
                paciente = new Paciente(nombrePaciente,
                        (Sexo) jCmbSexo.getSelectedItem(),
                        (int) jSprEdad.getValue(),
                        dueno,
                        especie,
                        raza);
                try {
                    Paciente.agregar(paciente);
                    modeloListaPacientes.clear();
                    modeloListaPacientes.addAll(Paciente.consultarPacientesPorDueño(dueno));
                    cambiarEstadoEspaciosPaciente(false);
                    jBtnLimpiarPaciente.setText("Cambiar de paciente");
                    JOptionPane.showMessageDialog(null, "El paciente fue agreado", "¡Paciente agregado!", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(JInternalProcesoCita.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Primero debes crear o elegir un dueño", "¡Dueño no definido!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnAnadirNuevoPacienteActionPerformed

    private void jCmbEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbEspecieActionPerformed
        // TODO add your handling code here:
        if (jCmbEspecie.getSelectedItem() instanceof Perro) {
            jCmbRaza.setModel(new DefaultComboBoxModel(arrayRazasPerros.toArray()));
        }
        else{
            jCmbRaza.setModel(new DefaultComboBoxModel(arrayRazasGatos.toArray()));
        }
    }//GEN-LAST:event_jCmbEspecieActionPerformed

    private void jBtnElegirPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElegirPacienteActionPerformed
        // TODO add your handling code here:
        if (jListPaciente.getSelectedIndex() != -1) {
            paciente = jListPaciente.getSelectedValue();
            jTxtNombrePaciente.setText(paciente.getNombre());
            jSprEdad.setValue(paciente.getEdad());
            jCmbSexo.setSelectedItem(paciente.getSexo());
            if (paciente.getEspecie().getId_especie() == 1) {
                jCmbEspecie.setSelectedIndex(0);
                for (Raza raza : arrayRazasPerros) {
                    if (paciente.getRaza().getId_raza() == raza.getId_raza()) {
                        jCmbRaza.setSelectedItem(raza);
                        break;
                    }
                }
            } else {
                jCmbEspecie.setSelectedIndex(1);
                for (Raza raza : arrayRazasGatos) {
                    if (paciente.getRaza().getId_raza() == raza.getId_raza()) {
                        jCmbRaza.setSelectedItem(raza);
                        break;
                    }
                }

            }
            cambiarEstadoEspaciosPaciente(false);
            jBtnLimpiarPaciente.setText("Cambiar de paciente");
            JOptionPane.showMessageDialog(null, "El paciente fue elegido correctamente", "Paciente elegido", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Debes elegir un paciente de la lista", "Paciente no elegido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnElegirPacienteActionPerformed

    private void cambiarEstadoEspaciosPaciente(boolean estado) {
        jTxtNombrePaciente.setEditable(estado);
        jSpinner1.setEnabled(estado);
        jCmbSexo.setEnabled(estado);
        jCmbEspecie.setEnabled(estado);
        jCmbRaza.setEnabled(estado);
        jBtnAnadirNuevoPaciente.setEnabled(estado);
        jBtnElegirPaciente.setEnabled(estado);
    }
    private void jBtnLimpiarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarPacienteActionPerformed
        // TODO add your handling code here:
        jTxtNombrePaciente.setText("");
        jSprEdad.setValue(0);
        jCmbSexo.setSelectedIndex(0);
        jCmbEspecie.setSelectedIndex(0);
        jCmbRaza.setSelectedIndex(0);
        paciente = null;
        if (jBtnLimpiarPaciente.getText().equals("Cambiar de paciente")) {
            cambiarEstadoEspaciosPaciente(true);
            jBtnLimpiarPaciente.setText("Limpiar");
        }
    }//GEN-LAST:event_jBtnLimpiarPacienteActionPerformed

    private void jTxtNombrePacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombrePacienteKeyTyped
        // TODO add your handling code here
    }//GEN-LAST:event_jTxtNombrePacienteKeyTyped

    private void jListMotivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListMotivosValueChanged
        // TODO add your handling code here:
        Motivo motivoSeleccionado = jListMotivos.getSelectedValue();
        if (motivoSeleccionado instanceof Vacunacion) {
            jTxtPrecioMotivo.setEditable(false);
            jCmbVacunas.setVisible(true);
            jLblVacunas.setVisible(true);
            jTxtPrecioMotivo.setText(((Vacuna)jCmbVacunas.getSelectedItem()).getPrecio() + "");
        }
        else if (motivoSeleccionado.getPrecio() != 0) {
            jTxtPrecioMotivo.setEditable(false);
            jCmbVacunas.setVisible(false);
            jTxtPrecioMotivo.setText(motivoSeleccionado.getPrecio() + "");
            jLblVacunas.setVisible(false);
        } else{
            jTxtPrecioMotivo.setEditable(true);
            jCmbVacunas.setVisible(false);
            jTxtPrecioMotivo.setText("");
            jLblVacunas.setVisible(false);
        }
    }//GEN-LAST:event_jListMotivosValueChanged

    private void jCmbVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbVacunasActionPerformed
        // TODO add your handling code here:
        jTxtPrecioMotivo.setText(((Vacuna)jCmbVacunas.getSelectedItem()).getPrecio() + "");
    }//GEN-LAST:event_jCmbVacunasActionPerformed

    private void jBtnAgregarMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarMotivoActionPerformed
        // TODO add your handling code here:
        if (jListMotivos.getSelectedIndex() != -1) {
            Motivo motivoSeleccionado = jListMotivos.getSelectedValue();
            if (motivoSeleccionado instanceof Vacunacion) {
                ((Vacunacion)motivoSeleccionado).setVacuna((Vacuna)jCmbVacunas.getSelectedItem());
            }
            else if (motivoSeleccionado.getPrecio() == 0) {
                try {
                    motivoSeleccionado.setPrecio(Double.parseDouble(jTxtPrecioMotivo.getText()));
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Debes ingresar un numero en el precio", "Espacio inválido", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            arrayMotivos.add(motivoSeleccionado);
            Object[] fila = {motivoSeleccionado, motivoSeleccionado.getPrecio()};
            modeloTablaMotivos.addRow(fila);
        }
    }//GEN-LAST:event_jBtnAgregarMotivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String hilera = "";
        for (Motivo motivo : arrayMotivos) {
            hilera += motivo.getDescripcion() + " ----- "+ motivo.getPrecio() + "\n";
        }
        JOptionPane.showMessageDialog(null, hilera);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCmbPruebasLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbPruebasLaboratorioActionPerformed
        // TODO add your handling code here:
        llenarListaSubCategorias();
    }//GEN-LAST:event_jCmbPruebasLaboratorioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jListSubCategorias.getSelectedIndex() != -1) {
            for (SubCategoriaPrueba subCategoria : arraySubCategorias) {
                if (jListSubCategorias.getSelectedValue().equals(subCategoria)) {
                    JOptionPane.showMessageDialog(null, "El tipo de prueba ya fue escogido", "Prueba ya elegida", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            arraySubCategorias.add(jListSubCategorias.getSelectedValue());
            JOptionPane.showMessageDialog(null, "El tipo de prueba fue elegido", "¡Prueba agregada!", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un tipo de prueba", "Prueba no elegida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String hilera = "";
        for (SubCategoriaPrueba subCategoria : arraySubCategorias) {
            hilera += subCategoria.getNombre()+ " ----- "+ subCategoria.getPrecio() + "\n";
        }
        JOptionPane.showMessageDialog(null, hilera);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtnEliminarMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarMotivoActionPerformed

    private void llenarListaSubCategorias() {
        modeloListaSubCategoriasPruebaLaboratorio.clear();
        for (SubCategoriaPrueba subCategoria : arrayTodasLasSubCategorias) {
            if (subCategoria.getId_prueba() == ((BLL_PruebaLaboratorio.PruebaLaboratorio) jCmbPruebasLaboratorio.getSelectedItem()).getId_prueba()) {
                modeloListaSubCategoriasPruebaLaboratorio.addElement(subCategoria);
            }
        }
    }
    
    private void llenarComboBoxPruebasLaboratorio() {
        try {
            jCmbPruebasLaboratorio.setModel(new DefaultComboBoxModel(PruebaLaboratorio.consultarPruebasLaboratorio().toArray()));
        } catch (SQLException ex) {
            Logger.getLogger(JInternalMantenimientoPruebasLaboratorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void accionesDefinirDueño() {
        jLblDuenoElegido.setText("Dueño: " + dueno.getNombre());
        cambiarEstadoEspaciosDueno(false);
        jBtnLimpiarDueno.setText("Cambiar dueño");
        try {
            modeloListaPacientes.clear();
            modeloListaPacientes.addAll(Paciente.consultarPacientesPorDueño(dueno));
        } catch (SQLException ex) {
            Logger.getLogger(JInternalProcesoCita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // </editor-fold>
    
    private void llenarListaMotivos(){
        try {
            modeloListaMotivos.addAll(Motivo.consultarMotivos());
        } catch (Exception ex) {
            Logger.getLogger(JInternalProcesoCita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregarMotivo;
    private javax.swing.JButton jBtnAnadirNuevoDueno;
    private javax.swing.JButton jBtnAnadirNuevoPaciente;
    private javax.swing.JButton jBtnElegirDueno;
    private javax.swing.JButton jBtnElegirPaciente;
    private javax.swing.JButton jBtnEliminarMotivo;
    private javax.swing.JButton jBtnEliminarPrueba;
    private javax.swing.JButton jBtnLimpiarDueno;
    private javax.swing.JButton jBtnLimpiarPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Especie> jCmbEspecie;
    private javax.swing.JComboBox<PruebaLaboratorio> jCmbPruebasLaboratorio;
    private javax.swing.JComboBox<Raza> jCmbRaza;
    private javax.swing.JComboBox<Sexo> jCmbSexo;
    private javax.swing.JComboBox<Vacuna> jCmbVacunas;
    private javax.swing.JFormattedTextField jFTxtNumeroCedula;
    private javax.swing.JFormattedTextField jFTxtNumeroTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblCedula;
    private javax.swing.JLabel jLblDireccion;
    private javax.swing.JLabel jLblDuenoElegido;
    private javax.swing.JLabel jLblDuenos;
    private javax.swing.JLabel jLblEdad;
    private javax.swing.JLabel jLblEdad1;
    private javax.swing.JLabel jLblEspecie;
    private javax.swing.JLabel jLblEspecie1;
    private javax.swing.JLabel jLblNombreDueno;
    private javax.swing.JLabel jLblNombrePaciente;
    private javax.swing.JLabel jLblNumeroTelefono;
    private javax.swing.JLabel jLblPacientes;
    private javax.swing.JLabel jLblSexoPaciente;
    private javax.swing.JLabel jLblVacunas;
    private javax.swing.JList<Dueño> jListDueno;
    private javax.swing.JList<Motivo> jListMotivos;
    private javax.swing.JList<Paciente> jListPaciente;
    private javax.swing.JList<SubCategoriaPrueba> jListSubCategorias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCita;
    private javax.swing.JPanel jPanelDatosPaciente;
    private javax.swing.JPanel jPanelDueno;
    private javax.swing.JPanel jPanelMotivo;
    private javax.swing.JPanel jPanelMotivosElegidos;
    private javax.swing.JPanel jPanelPaciente;
    private javax.swing.JPanel jPanelPrueba;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSprEdad;
    private javax.swing.JTabbedPane jTPlProcesoCita;
    private javax.swing.JTable jTableMotivosElegidos;
    private javax.swing.JTable jTablePruebasElegidas;
    private javax.swing.JTextField jTxtDireccionDueno;
    private javax.swing.JTextField jTxtNombreDueno;
    private javax.swing.JTextField jTxtNombrePaciente;
    private javax.swing.JTextField jTxtPrecioMotivo;
    // End of variables declaration//GEN-END:variables
}
