/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;

import BLL.Cita;
import BLL.Paciente;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class JInternalListaCitasPorPaciente extends javax.swing.JInternalFrame {

    DefaultTableModel modeloTablaPacientes;
    DefaultTableModel modeloTablaCitas;
    /**
     * Creates new form JInternalLisraCitasPorPaciente
     */
    public JInternalListaCitasPorPaciente() {
        initComponents();
        modeloTablaPacientes = (DefaultTableModel)jTablePacientes.getModel();
        modeloTablaCitas = (DefaultTableModel)jTableCitas.getModel();
        llenarTablaPacientes();
    }

    private void llenarTablaPacientes(){
        try {
            for (Paciente paciente : Cita.consultarPacientesConCita()) {
                Object [] fila = {paciente.getDueño().getNombre(), paciente.getDueño().getCedula(), paciente};
                modeloTablaPacientes.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JInternalListaCitasPorPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBtnElegirPaciente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCitas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jBtnMostarInformacion = new javax.swing.JButton();
        jBtnMostarInformacion1 = new javax.swing.JButton();

        setClosable(true);

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dueño", "Cedula", "Paciente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pacientes");

        jBtnElegirPaciente.setText("Elegir paciente");
        jBtnElegirPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElegirPacienteActionPerformed(evt);
            }
        });

        jTableCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Motivo", "Evaluaciones", "Pruebas de laboratorio", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableCitas);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Citas");

        jBtnMostarInformacion.setText("Mostrar mas informacion");
        jBtnMostarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMostarInformacionActionPerformed(evt);
            }
        });

        jBtnMostarInformacion1.setText("Mostra factura");
        jBtnMostarInformacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMostarInformacion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnElegirPaciente)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnMostarInformacion1)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnMostarInformacion))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnElegirPaciente)
                    .addComponent(jBtnMostarInformacion)
                    .addComponent(jBtnMostarInformacion1))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnElegirPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElegirPacienteActionPerformed
        // TODO add your handling code here:
        modeloTablaCitas.setRowCount(0);
        if (jTablePacientes.getSelectedRow() != -1) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm");

            Paciente paciente = (Paciente) jTablePacientes.getValueAt(jTablePacientes.getSelectedRow(), 2);
            if (paciente.getArrayCitas().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El paciente no tiene ninguna cita", "Paciente sin citas", JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (Cita cita : paciente.getArrayCitas()) {

                    Object[] fila = new Object[5];

                    String formattedDate = sdf.format(cita.getFechaCita());

                    fila[0] = formattedDate;
                    if (cita.getArrayMotivo().isEmpty()) {
                        fila[1] = "No hay motivos";
                    } else {
                        fila[1] = cita.getArrayMotivo().size();
                    }
                    if (cita.getArrayEvaluacion().isEmpty()) {
                        fila[2] = "No hay evaluaciones";
                    } else {
                        fila[2] = cita.getArrayEvaluacion().size();
                    }
                    if (cita.getArrayPruebaLaboratorio().isEmpty()) {
                        fila[3] = "No hay pruebas de laboratorio";
                    } else {
                        fila[3] = cita.getArrayPruebaLaboratorio().size();
                    }

                    fila[4] = cita;

                    modeloTablaCitas.addRow(fila);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes elegir un paciente de la lista", "Paciente no elegido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnElegirPacienteActionPerformed

    private void jBtnMostarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMostarInformacionActionPerformed
        // TODO add your handling code here:
        int fila = jTableCitas.getSelectedRow();
        if (fila != -1) {
            JOptionPane.showMessageDialog(null, ((Cita)modeloTablaCitas.getValueAt(fila, 4)).toStringInformacion());
        }
        else{
            JOptionPane.showMessageDialog(null, "Debes elegir una cita de la lista", "Cita no elegida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnMostarInformacionActionPerformed

    private void jBtnMostarInformacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMostarInformacion1ActionPerformed
        // TODO add your handling code here:
        int fila = jTableCitas.getSelectedRow();
        if (fila != -1) {
            JOptionPane.showMessageDialog(null, ((Cita)modeloTablaCitas.getValueAt(fila, 4)).mostrarPrecio());
        }
        else{
            JOptionPane.showMessageDialog(null, "Debes elegir una cita de la lista", "Cita no elegida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnMostarInformacion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElegirPaciente;
    private javax.swing.JButton jBtnMostarInformacion;
    private javax.swing.JButton jBtnMostarInformacion1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCitas;
    private javax.swing.JTable jTablePacientes;
    // End of variables declaration//GEN-END:variables
}
