/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package UI;

import javax.swing.JFrame;

/**
 *
 * @author andrey
 */
public class MdiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MdiPrincipal
     * @param nombreUsuario
     */
    public MdiPrincipal(String nombreUsuario) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle(nombreUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        ProcesosMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        ReportesMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        MantenimientoMenu = new javax.swing.JMenu();
        jMItemEspeciesRazas = new javax.swing.JMenuItem();
        jMItemMotivos = new javax.swing.JMenuItem();
        jMItemPruebaLaboratorio = new javax.swing.JMenuItem();
        jMItemVacuna = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProcesosMenu.setMnemonic('f');
        ProcesosMenu.setText("Procesos");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        ProcesosMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        ProcesosMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        ProcesosMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        ProcesosMenu.add(exitMenuItem);

        menuBar.add(ProcesosMenu);

        ReportesMenu.setMnemonic('e');
        ReportesMenu.setText("Reportes");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        ReportesMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        ReportesMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        ReportesMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        ReportesMenu.add(deleteMenuItem);

        menuBar.add(ReportesMenu);

        MantenimientoMenu.setMnemonic('h');
        MantenimientoMenu.setText("Mantenimiento");

        jMItemEspeciesRazas.setMnemonic('c');
        jMItemEspeciesRazas.setText("Especies y razas");
        jMItemEspeciesRazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemEspeciesRazasActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(jMItemEspeciesRazas);

        jMItemMotivos.setMnemonic('a');
        jMItemMotivos.setText("Motivos");
        jMItemMotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemMotivosActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(jMItemMotivos);

        jMItemPruebaLaboratorio.setText("Pruebas de laboratorio");
        jMItemPruebaLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemPruebaLaboratorioActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(jMItemPruebaLaboratorio);

        jMItemVacuna.setText("Vacunas");
        jMItemVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemVacunaActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(jMItemVacuna);

        menuBar.add(MantenimientoMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jMItemEspeciesRazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemEspeciesRazasActionPerformed
        // TODO add your handling code here:
        JInternalMantenimientoEspeciesRazas jInternalMantenimientoEspeciesRazas = new JInternalMantenimientoEspeciesRazas();
        desktopPane.add(jInternalMantenimientoEspeciesRazas);
        jInternalMantenimientoEspeciesRazas.setVisible(true);
    }//GEN-LAST:event_jMItemEspeciesRazasActionPerformed

    private void jMItemMotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemMotivosActionPerformed
        // TODO add your handling code here:
        jInternalMantenimientoMotivos ventana = new jInternalMantenimientoMotivos();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMItemMotivosActionPerformed

    private void jMItemVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemVacunaActionPerformed
        // TODO add your handling code here:
        JInternalMantenimientoVacunas ventana = new JInternalMantenimientoVacunas();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMItemVacunaActionPerformed

    private void jMItemPruebaLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemPruebaLaboratorioActionPerformed
        // TODO add your handling code here:
        JInternalMantenimientoPruebasLaboratorio ventana = new JInternalMantenimientoPruebasLaboratorio();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMItemPruebaLaboratorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MantenimientoMenu;
    private javax.swing.JMenu ProcesosMenu;
    private javax.swing.JMenu ReportesMenu;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem jMItemEspeciesRazas;
    private javax.swing.JMenuItem jMItemMotivos;
    private javax.swing.JMenuItem jMItemPruebaLaboratorio;
    private javax.swing.JMenuItem jMItemVacuna;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
