/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package UI;

import javax.swing.JFrame;

/**
 *
 * @author andrey
 */
public class MdiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MdiPrincipal
     * @param nombreUsuario
     */
    public MdiPrincipal(String nombreUsuario) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle(nombreUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new DesktopConFondo("/Imagenes/FondoMdiPrincipal.png");
        menuBar = new javax.swing.JMenuBar();
        ProcesosMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        ReportesMenu = new javax.swing.JMenu();
        MnItemListaPacientes = new javax.swing.JMenuItem();
        MnItemListaCitasPorPaciente = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        MantenimientoMenu = new javax.swing.JMenu();
        jMItemEspeciesRazas = new javax.swing.JMenuItem();
        jMItemMotivos = new javax.swing.JMenuItem();
        jMItemVacuna = new javax.swing.JMenuItem();
        jMItemPruebaLaboratorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        desktopPane.setOpaque(false);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1135, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPane);

        ProcesosMenu.setMnemonic('f');
        ProcesosMenu.setText("Procesos");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Proceso de cita");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        ProcesosMenu.add(openMenuItem);

        menuBar.add(ProcesosMenu);

        ReportesMenu.setMnemonic('e');
        ReportesMenu.setText("Reportes");

        MnItemListaPacientes.setMnemonic('t');
        MnItemListaPacientes.setText("Lista de pacientes");
        MnItemListaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemListaPacientesActionPerformed(evt);
            }
        });
        ReportesMenu.add(MnItemListaPacientes);

        MnItemListaCitasPorPaciente.setMnemonic('y');
        MnItemListaCitasPorPaciente.setText("Lista de citas por paciente");
        MnItemListaCitasPorPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemListaCitasPorPacienteActionPerformed(evt);
            }
        });
        ReportesMenu.add(MnItemListaCitasPorPaciente);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Lista de citas por fecha");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        ReportesMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Resumen de cita por paciente");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        ReportesMenu.add(deleteMenuItem);

        menuBar.add(ReportesMenu);

        MantenimientoMenu.setMnemonic('h');
        MantenimientoMenu.setText("Mantenimiento");

        jMItemEspeciesRazas.setMnemonic('c');
        jMItemEspeciesRazas.setText("Especies y razas");
        jMItemEspeciesRazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemEspeciesRazasActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(jMItemEspeciesRazas);

        jMItemMotivos.setMnemonic('a');
        jMItemMotivos.setText("Motivos");
        jMItemMotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemMotivosActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(jMItemMotivos);

        jMItemVacuna.setText("Vacunas");
        jMItemVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemVacunaActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(jMItemVacuna);

        jMItemPruebaLaboratorio.setText("Pruebas de laboratorio");
        jMItemPruebaLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemPruebaLaboratorioActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(jMItemPruebaLaboratorio);

        menuBar.add(MantenimientoMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMItemEspeciesRazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemEspeciesRazasActionPerformed
        // TODO add your handling code here:
        JInternalMantenimientoEspeciesRazas jInternalMantenimientoEspeciesRazas = new JInternalMantenimientoEspeciesRazas();
        desktopPane.add(jInternalMantenimientoEspeciesRazas);
        jInternalMantenimientoEspeciesRazas.setVisible(true);
    }//GEN-LAST:event_jMItemEspeciesRazasActionPerformed

    private void jMItemMotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemMotivosActionPerformed
        // TODO add your handling code here:
        jInternalMantenimientoMotivos ventana = new jInternalMantenimientoMotivos();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMItemMotivosActionPerformed

    private void jMItemVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemVacunaActionPerformed
        // TODO add your handling code here:
        JInternalMantenimientoVacunas ventana = new JInternalMantenimientoVacunas();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMItemVacunaActionPerformed

    private void jMItemPruebaLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemPruebaLaboratorioActionPerformed
        // TODO add your handling code here:
        JInternalMantenimientoPruebasLaboratorio ventana = new JInternalMantenimientoPruebasLaboratorio();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMItemPruebaLaboratorioActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        JInternalProcesoCita ventana = new JInternalProcesoCita();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void MnItemListaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemListaPacientesActionPerformed
        // TODO add your handling code here:
        JInternalFrameListaPacientes ventana = new JInternalFrameListaPacientes();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_MnItemListaPacientesActionPerformed

    private void MnItemListaCitasPorPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemListaCitasPorPacienteActionPerformed
        // TODO add your handling code here:
        JInternalListaCitasPorPaciente ventana = new JInternalListaCitasPorPaciente();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_MnItemListaCitasPorPacienteActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        // TODO add your handling code here:
        JInternalListaCitasPorFecha ventana = new JInternalListaCitasPorFecha();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        // TODO add your handling code here:
        JInternalResumenCitaPorPaciente ventana = new JInternalResumenCitaPorPaciente();
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_deleteMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MantenimientoMenu;
    private javax.swing.JMenuItem MnItemListaCitasPorPaciente;
    private javax.swing.JMenuItem MnItemListaPacientes;
    private javax.swing.JMenu ProcesosMenu;
    private javax.swing.JMenu ReportesMenu;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jMItemEspeciesRazas;
    private javax.swing.JMenuItem jMItemMotivos;
    private javax.swing.JMenuItem jMItemPruebaLaboratorio;
    private javax.swing.JMenuItem jMItemVacuna;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
